name: medicine_tracker
description: A medicine tracker app using BLoC state management and Dio for HTTP requests.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^8.1.4
  bloc: ^8.1.4
  equatable: ^2.0.5

  # HTTP client
  dio: ^5.4.0

  # UI
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpg
